### ISSUE TITLE
Could not get the block callback when the server response 403

### ISSUE THREAD

**Issue by siriuscn** [kylehickinson/FastImage#1]
Thanks for you nice library!
But I found a issue.

If the server response 403, and contains http body(such as nginx), the block won't be called with error.
- (BOOL)parseRequest:(_KHIFIRequest *)request
  {
  NSData *data = request.data;//[request.data copy];
  
  // Get the type
  KHIFastImageType type = [self typeForImageData:data];
  if (type != KHIFastImageTypeUnsupported) {
  ....
  }
  return YES;

You pass the YES, and then the requests remove the key.

Thus - (void)URLSession:(NSURLSession *)session task:(NSURLSessionTask *)task didCompleteWithError:(NSError *)error
will not call the block.

**Comment by kylehickinson** [comment]
Hey, thanks for the heads up :)

Do you have an example image URL I could use to reproduce this?

**Comment by siriuscn** [comment]
I am sorry for that I could not supply the actual url in the debugging app due to business secureity limit.
But I found another public URL to reproduce it (server responses 404, the same as 403)
http://api.douban.com/noteimage/id=p32395366-2&site=www.mysite.com&key=23432453454354

The same issue.:)
